import React, { createContext, useContext, useState } from 'react';

// Language translations
const translations = {
  en: {
    // Navigation
    home: 'Home',
    services: 'Services',
    help: 'Help',
    contact: 'Contact',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    language: 'Language',
    oneplatform: 'One Platform for All',
    citizenservices: 'Citizen Services',
    tagline: 'Access all government services in one place. Pay bills, apply for permits, check status, and more.',
    secure: '100% Secure',
    available: '24/7 Available',
    easyuse: 'Easy to Use',
    getstarted: 'Get Started',
    learnmore: 'Learn More',
    signin: 'Sign In',
    signinDesc: 'Access your account and manage all your services',
    createaccount: 'Create Account',
    createaccountDesc: 'Create a new account to get started with SUVIDHA',
    quickpay: 'Quick Pay',
    quickpayDesc: 'Pay bills without creating an account',
    servicesDesc: 'Comprehensive solutions for all your government service needs',
    electricity: 'Electricity',
    electricityDesc: 'Pay your electricity bills, check consumption, and manage connections online.',
    water: 'Water Supply',
    waterDesc: 'Water bill payments, connection requests, and service issues.',
    gas: 'Gas Connection',
    gasDesc: 'Apply for new gas connection or manage existing connections.',
    municipal: 'Municipal Services',
    municipalDesc: 'Property tax, permits, licenses, and other municipal services.',
    taxes: 'Property Tax',
    taxesDesc: 'Calculate, pay property tax and get certificates online.',
    licenses: 'Licenses & Permits',
    licensesDesc: 'Apply for business licenses, trade permits, and certifications.',
    announcements: 'Announcements & Updates',
    announcementsDesc: 'Stay informed about important government notices and service updates',
    citizens: 'Citizens Served',
    servicesAvailable: 'Services Available',
    transactions: 'Daily Transactions',
    satisfaction: 'Satisfaction Rate',
    step: 'Step',
    of: 'of',
    next: 'Next',
    back: 'Back',
    continue: 'Continue',
    skip: 'Skip',
    done: 'Done',
    selectService: 'Select Service',
    enterDetails: 'Enter Details',
    review: 'Review',
    complete: 'Complete',
    selectServiceGuide: 'Choose a service from the options below',
    enterDetailsGuide: 'Fill in the required information',
    reviewGuide: 'Check your details before submitting',
    completeGuide: 'Your request has been submitted',
    howToUse: 'How to use this service:',
    apply: 'Apply Now',
    less: 'View Less',
    readyToStart: 'Ready to Get Started?',
    joinMillions: 'Join millions of citizens using SUVIDHA for seamless government services',
    searchPlaceholder: 'Search services...',
    // Tour Guide
    tourWelcomeTitle: 'Welcome to SUVIDHA',
    tourWelcomeContent: 'Your one-stop portal for all government utility services. Let us show you around!',
    tourSearchTitle: 'Smart Search',
    tourSearchContent: 'Quickly find the service you need by typing keywords like "Water" or "Bill".',
    tourQuickTitle: 'Quick Actions',
    tourQuickContent: 'Fast access to Login, Sign Up, and Quick Pay without navigating deep into menus.',
    tourServicesTitle: 'Our Services',
    tourServicesContent: 'Explore all available services like Electricity, Water, and Sanitation here.',
    finish: 'Finish',
    tutorial: 'Quick Tutorial',
    startTutorial: 'Start Tutorial',
    skipTutorial: 'Skip Tutorial',
    needHelp: 'Need Help?',
    previous: 'Previous',
    helpfulTips: 'Helpful Tips',
    quickActions: 'Quick Actions',
  },
  hi: {
    home: 'होम',
    services: 'सेवाएं',
    help: 'मदद',
    contact: 'संपर्क करें',
    signIn: 'साइन इन करें',
    signUp: 'साइन अप करें',
    language: 'भाषा',
    oneplatform: 'सभी के लिए एक प्लेटफॉर्म',
    citizenservices: 'नागरिक सेवाएं',
    tagline: 'एक ही जगह पर सभी सरकारी सेवाओं तक पहुंचें। बिल भुगतान करें, परमिट के लिए आवेदन करें, स्थिति जांचें, और बहुत कुछ।',
    secure: '100% सुरक्षित',
    available: '24/7 उपलब्ध',
    easyuse: 'उपयोग में आसान',
    getstarted: 'शुरुआत करें',
    learnmore: 'अधिक जानें',
    signin: 'साइन इन करें',
    signinDesc: 'अपने खाते तक पहुंचें और अपनी सभी सेवाओं को प्रबंधित करें',
    createaccount: 'खाता बनाएं',
    createaccountDesc: 'SUVIDHA के साथ शुरुआत करने के लिए एक नया खाता बनाएं',
    quickpay: 'त्वरित भुगतान',
    quickpayDesc: 'खाता बनाए बिना बिल का भुगतान करें',
    servicesDesc: 'सभी सरकारी सेवा की आवश्यकताओं के लिए व्यापक समाधान',
    electricity: 'बिजली',
    electricityDesc: 'अपने बिजली बिल का भुगतान करें, खपत जांचें और ऑनलाइन कनेक्शन प्रबंधित करें।',
    water: 'जल आपूर्ति',
    waterDesc: 'जल बिल भुगतान, कनेक्शन अनुरोध और सेवा समस्याएं।',
    gas: 'गैस कनेक्शन',
    gasDesc: 'नया गैस कनेक्शन के लिए आवेदन करें या मौजूदा कनेक्शन प्रबंधित करें।',
    municipal: 'नगरपालिका सेवाएं',
    municipalDesc: 'संपत्ति कर, परमिट, लाइसेंस और अन्य नगरपालिका सेवाएं।',
    taxes: 'संपत्ति कर',
    taxesDesc: 'संपत्ति कर की गणना करें, भुगतान करें और ऑनलाइन प्रमाणपत्र प्राप्त करें।',
    licenses: 'लाइसेंस और परमिट',
    licensesDesc: 'व्यावसायिक लाइसेंस, व्यापार परमिट और प्रमाणपत्र के लिए आवेदन करें।',
    announcements: 'घोषणाएं और अपडेट',
    announcementsDesc: 'महत्वपूर्ण सरकारी नोटिस और सेवा अपडेट के बारे में सूचित रहें',
    citizens: 'नागरिकों की सेवा की गई',
    servicesAvailable: 'उपलब्ध सेवाएं',
    transactions: 'दैनिक लेनदेन',
    satisfaction: 'संतुष्टि दर',
    step: 'चरण',
    of: 'का',
    next: 'अगला',
    back: 'पीछे',
    continue: 'जारी रखें',
    skip: 'छोड़ें',
    done: 'पूर्ण',
    selectService: 'सेवा चुनें',
    enterDetails: 'विवरण दर्ज करें',
    review: 'समीक्षा',
    complete: 'पूर्ण',
    selectServiceGuide: 'नीचे दिए गए विकल्पों में से एक सेवा चुनें',
    enterDetailsGuide: 'आवश्यक जानकारी भरें',
    reviewGuide: 'जमा करने से पहले अपने विवरण की जांच करें',
    completeGuide: 'आपका अनुरोध जमा कर दिया गया है',
    howToUse: 'इस सेवा का उपयोग कैसे करें:',
    apply: 'अभी आवेदन करें',
    less: 'कम दिखाएं',
    readyToStart: 'शुरुआत करने के लिए तैयार हैं?',
    joinMillions: 'SUVIDHA का उपयोग करके सरकारी सेवाओं का आसान उपयोग करें',
    searchPlaceholder: 'सेवाएं खोजें...',
    // Tour Guide
    tourWelcomeTitle: 'SUVIDHA में आपका स्वागत है',
    tourWelcomeContent: 'सभी सरकारी सेवाओं के लिए आपका वन-स्टॉप पोर्टल। आइए हम आपको दिखाते हैं!',
    tourSearchTitle: 'स्मार्ट सर्च',
    tourSearchContent: 'कीवर्ड टाइप करके अपनी ज़रूरत की सेवा तुरंत खोजें।',
    tourQuickTitle: 'त्वरित कार्रवाई',
    tourQuickContent: 'मेन्यू में गहराई तक जाए बिना लॉगिन, साइन अप और त्वरित भुगतान तक तेजी से पहुंचें।',
    tourServicesTitle: 'हमारी सेवाएं',
    tourServicesContent: 'बिजली, पानी और स्वच्छता जैसी सभी उपलब्ध सेवाओं का यहां अन्वेषण करें।',
    finish: 'समाप्त',
    tutorial: 'त्वरित ट्यूटोरियल',
    startTutorial: 'ट्यूटोरियल शुरू करें',
    skipTutorial: 'ट्यूटोरियल छोड़ें',
    needHelp: 'मदद चाहिए?',
    previous: 'पिछला',
    helpfulTips: 'उपयोगी टिप्स',
    quickActions: 'त्वरित कार्रवाई',
  },
  regional: {
    home: 'होम',
    services: 'सेवा',
    help: 'सहायता',
    contact: 'संपर्क',
    signIn: 'लॉगिन',
    signUp: 'नया अकाउंट',
    language: 'भाषा',
    oneplatform: 'सरकारी सेवा',
    citizenservices: 'एक जगह पर',
    tagline: 'सभी सरकारी काम एक ऐप में करें।',
    secure: 'सुरक्षित',
    available: 'हमेशा खुला',
    easyuse: 'आसान',
    getstarted: 'शुरुआत करें',
    learnmore: 'जानकारी',
    signin: 'लॉगिन',
    signinDesc: 'अपना अकाउंट खोलें',
    createaccount: 'नया अकाउंट',
    createaccountDesc: 'नया अकाउंट बनाएं',
    quickpay: 'तेजी से भुगतान',
    quickpayDesc: 'बिना अकाउंट के बिल भुगतान करें',
    servicesDesc: 'सभी सरकारी सेवाएं',
    electricity: 'बिजली',
    electricityDesc: 'बिल भुगतान करें',
    water: 'पानी',
    waterDesc: 'जल बिल भुगतान करें',
    gas: 'गैस',
    gasDesc: 'गैस कनेक्शन लें',
    municipal: 'शहर सेवा',
    municipalDesc: 'कर और परमिट',
    taxes: 'कर',
    taxesDesc: 'संपत्ति कर भुगतान करें',
    licenses: 'परमिट',
    licensesDesc: 'परमिट के लिए आवेदन करें',
    announcements: 'सूचनाएं',
    announcementsDesc: 'नई घोषणाएं और सूचनाएं',
    citizens: 'लोगों को सेवा',
    servicesAvailable: 'सेवाएं',
    transactions: 'रोजाना लेन-देन',
    satisfaction: 'संतुष्टि',
    step: 'कदम',
    of: 'में से',
    next: 'अगला',
    back: 'वापस',
    continue: 'जारी रखें',
    skip: 'छोड़ें',
    done: 'पूरा',
    selectService: 'सेवा चुनें',
    enterDetails: 'जानकारी दें',
    review: 'जांचें',
    complete: 'पूरा हुआ',
    selectServiceGuide: 'एक सेवा चुनें',
    enterDetailsGuide: 'जानकारी भरें',
    reviewGuide: 'जानकारी की जांच करें',
    completeGuide: 'आपका काम पूरा हो गया',
    howToUse: 'इस सेवा का उपयोग कैसे करें:',
    apply: 'अभी आवेदन करें',
    less: 'कम दिखाएं',
    readyToStart: 'शुरुआत करने के लिए तैयार?',

    joinMillions: 'लाखों लोग SUVIDHA का उपयोग करते हैं',
    searchPlaceholder: 'सेवा खोजें...',
    // Tour Guide
    tourWelcomeTitle: 'SUVIDHA में स्वागत',
    tourWelcomeContent: 'सभी सरकारी काम एक जगह। चलिए देखते हैं!',
    tourSearchTitle: 'खोजें',
    tourSearchContent: 'अपनी सेवा खोजने के लिए यहाँ लिखें।',
    tourQuickTitle: 'जल्दी काम',
    tourQuickContent: 'लॉगिन और बिल पेमेंट जल्दी से करें।',
    tourServicesTitle: 'सेवाएं',
    tourServicesContent: 'बिजली, पानी, और अन्य सेवाएं यहाँ देखें।',
    finish: 'खतम',
    tutorial: 'ट्यूटोरियल',
    startTutorial: 'ट्यूटोरियल शुरू करें',
    skipTutorial: 'छोड़ें',
    needHelp: 'मदद?',
    previous: 'पहले',
    helpfulTips: 'टिप्स',
    quickActions: 'जल्दी काम',
  },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const t = (key) => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

export default LanguageContext;
